
import { TestBed } from '@angular/core/testing';

import { MeteoService } from './meteo.service';
import { HttpClient, HttpClientModule } from '@angular/common/http';

describe('MeteoService', () => {
  let service: MeteoService;
  let client: HttpClient;

  beforeEach(() => {
    TestBed.configureTestingModule({
<<<<<<< HEAD
      imports:[
        HttpClientModule,

      ],

    });

    client = TestBed.inject(HttpClient);

=======
      imports: [HttpClientModule],
    });

    client = TestBed.inject(HttpClient);
>>>>>>> adcf55854059527e461402a4ea8ff564880a9a6b
    service = TestBed.inject(MeteoService);
  });


  it('should be created', () => {
    expect(service).toBeTruthy();
  });

<<<<<<< HEAD
  it('should create forecast array', () =>{
    const testObj = {
      {
        "latitude": 44.4,
        "longitude": 8.940001,
        "generationtime_ms": 0.2460479736328125,
        "utc_offset_seconds": 0,
        "timezone": "GMT",
        "timezone_abbreviation": "GMT",
        "elevation": 18,
        "hourly_units": {
            "time": "iso8601",
            "temperature_2m": "°C",
            "relativehumidity_2m": "%",
            "precipitation_probability": "%",
            "weathercode": "wmo code",
            "cloudcover": "%",
            "windspeed_10m": "km/h"
        },
        "hourly": {
            "time": [
                "2023-10-09T00:00",
                "2023-10-09T01:00",
                "2023-10-09T02:00",

            ],
            "temperature_2m": [
                19.5,
                19.4,
                18.9,

            ],
            "relativehumidity_2m": [
                93,
                94,
                94,
                97,
                96,
                97,
                92,
                90,
                86,
                83,
                81,
                77,
                76,
                77,
                78,
                80,
                82,
                85,
                88,
                92,
                92,
                89,
                90,
                90,
                90,
                89,
                88,
                90,
                89,
                90,
                90,
                86,
                78,
                72,
                72,
                75,
                74,
                73,
                73,
                78,
                80,
                83,
                85,
                88,
                88,
                89,
                89,
                90,
                90,
                90,
                91,
                91,
                91,
                90,
                90,
                94,
                84,
                77,
                75,
                75,
                74,
                75,
                75,
                77,
                80,
                83,
                86,
                86,
                87,
                92,
                95,
                95,
                94,
                92,
                92,
                93,
                93,
                92,
                93,
                91,
                89,
                86,
                81,
                75,
                71,
                70,
                70,
                72,
                76,
                81,
                85,
                88,
                89,
                91,
                92,
                93,
                94,
                95,
                95,
                95,
                94,
                93,
                91,
                87,
                81,
                77,
                76,
                77,
                78,
                77,
                77,
                77,
                80,
                83,
                86,
                87,
                88,
                88,
                88,
                89,
                89,
                86,
                86,
                86,
                87,
                88,
                88,
                86,
                84,
                81,
                79,
                77,
                76,
                76,
                77,
                79,
                81,
                83,
                85,
                87,
                89,
                90,
                90,
                90,
                90,
                89,
                88,
                87,
                87,
                87,
                87,
                85,
                81,
                79,
                78,
                78,
                78,
                78,
                79,
                79,
                80,
                80,
                81,
                82,
                82,
                83,
                84,
                86
            ],
            "precipitation_probability": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                3,
                5,
                8,
                10,
                9,
                7,
                6,
                5,
                4,
                3,
                5,
                8,
                10,
                16,
                23,
                29,
                35,
                42,
                48,
                50,
                53,
                55,
                54,
                53,
                52,
                51,
                49,
                48,
                49,
                51,
                52,
                46,
                41,
                35,
                29,
                22,
                16,
                18,
                21,
                23,
                23,
                23
            ],
            "weathercode": [
                2,
                45,
                45,
                45,
                45,
                45,
                45,
                3,
                3,
                3,
                2,
                2,
                1,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                3,
                3,
                2,
                2,
                1,
                2,
                2,
                3,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                3,
                2,
                3,
                3,
                3,
                2,
                80,
                3,
                3,
                3,
                2,
                2,
                2,
                3,
                3,
                3,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                80,
                80,
                80,
                80,
                80,
                80,
                80,
                80,
                80,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                3,
                3,
                80,
                80,
                80,
                80,
                80,
                80,
                80,
                80,
                80,
                2,
                2,
                2,
                3,
                3,
                3,
                2,
                2,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                3,
                3,
                80,
                80
            ],
            "cloudcover": [
                82,
                62,
                31,
                47,
                88,
                86,
                90,
                85,
                82,
                96,
                78,
                53,
                41,
                61,
                65,
                67,
                65,
                70,
                79,
                78,
                74,
                53,
                100,
                100,
                100,
                100,
                100,
                97,
                56,
                43,
                34,
                69,
                67,
                89,
                66,
                74,
                77,
                91,
                95,
                78,
                67,
                76,
                78,
                57,
                84,
                62,
                40,
                58,
                63,
                63,
                58,
                75,
                66,
                75,
                52,
                75,
                76,
                71,
                70,
                70,
                68,
                66,
                59,
                61,
                57,
                63,
                65,
                66,
                72,
                65,
                67,
                81,
                85,
                87,
                82,
                83,
                87,
                90,
                87,
                85,
                83,
                81,
                77,
                74,
                70,
                68,
                67,
                65,
                67,
                69,
                71,
                70,
                69,
                68,
                70,
                71,
                73,
                74,
                74,
                75,
                68,
                62,
                55,
                66,
                76,
                87,
                79,
                71,
                63,
                65,
                68,
                70,
                69,
                67,
                66,
                72,
                78,
                84,
                82,
                80,
                78,
                79,
                83,
                86,
                87,
                87,
                88,
                81,
                73,
                66,
                65,
                64,
                63,
                75,
                88,
                100,
                97,
                94,
                91,
                94,
                97,
                100,
                96,
                93,
                89,
                90,
                91,
                92,
                87,
                81,
                76,
                78,
                81,
                83,
                77,
                72,
                66,
                71,
                76,
                81,
                87,
                94,
                100,
                100,
                100,
                100,
                100,
                100
            ],
            "windspeed_10m": [
                2.1,
                3.3,
                4.5,
                5.3,
                5.2,
                5.8,
                6.8,
                6,
                2.6,
                6.4,
                8.2,
                9.1,
                9.7,
                9.6,
                8.8,
                7.7,
                5.9,
                4.2,
                2.5,
                2.5,
                4.9,
                6.3,
                7.3,
                7.6,
                8,
                7.6,
                7.6,
                7.5,
                7.6,
                7.6,
                8,
                7.2,
                3.5,
                4.3,
                7.3,
                9.6,
                9.4,
                10.2,
                9.6,
                7.9,
                7.7,
                4.1,
                3.4,
                5.1,
                6.3,
                6.3,
                6.8,
                6.8,
                6.8,
                7,
                7,
                7.4,
                7.6,
                7.1,
                7.2,
                3.2,
                1.8,
                4.9,
                7.2,
                7.6,
                7.2,
                8.3,
                6.5,
                5.8,
                4.3,
                2.1,
                1.6,
                2.3,
                2.6,
                3.7,
                4.3,
                4,
                3.9,
                4.3,
                3.9,
                3.9,
                3.7,
                3.7,
                3.6,
                2.2,
                4.5,
                7.2,
                8.1,
                8,
                8,
                8.7,
                9,
                8.6,
                6.8,
                4,
                1.9,
                0.8,
                0.5,
                1.1,
                2.3,
                3.7,
                4.7,
                5,
                5.2,
                5.2,
                5.5,
                6.2,
                5.5,
                3.5,
                1.5,
                3.7,
                6.2,
                8.2,
                9.3,
                9.2,
                8,
                6.8,
                5.4,
                3.7,
                2.7,
                2.6,
                3.1,
                3.6,
                3.8,
                4.2,
                4.3,
                5.1,
                5.8,
                6.4,
                6.3,
                6.2,
                5.8,
                5.6,
                6.4,
                7.4,
                7.9,
                8.2,
                8.4,
                8.4,
                8.1,
                7.9,
                7.7,
                7.1,
                7.1,
                7.2,
                7.1,
                6.9,
                6.5,
                6.1,
                5.5,
                5.4,
                5.2,
                5.4,
                5.9,
                6.9,
                6.4,
                4.1,
                3.1,
                5.4,
                6.7,
                7.4,
                7.9,
                8.2,
                8.7,
                8.7,
                8.4,
                8.4,
                8.1,
                8,
                8.1,
                8.3,
                8.3,
                8.6
            ]
        }
    }

    }
    const array = service.createForecastArray(testObj);

    expect(array).toBeTruthy()

  })

  it('forecast array should have 3 elements', ()=>{
    const testObj = {

    }
    const array = service.createForecastArray(testObj);
    expect(array.length)toEquel(3);

  })
=======
  it('should create forecast array', () => {
    const testObj = {
      hourly_units: {
        temperature_2m: '°C',
        relativehumidity_2m: '%',
        precipitation_probability: '%',
        cloudcover: '%',
        windspeed_10m: 'km/h',
      },
      hourly: {
        time: ['2023-10-09T00:00', '2023-10-09T01:00', '2023-10-09T02:00'],
        temperature_2m: [19.5, 19.4, 18.9],
        relativehumidity_2m: [93, 94, 94],
        precipitation_probability: [0, 0, 0],
        weathercode: [2, 45, 45],
        cloudcover: [82, 62, 31],
        windspeed_10m: [2.1, 3.3, 4.5],
      },
    };

    const array = service.createForecastArray(testObj);

    expect(array).toBeTruthy();
  });

  it('forecast array shuold have 3 elements', () => {
    const testObj = {
      hourly_units: {
        temperature_2m: '°C',
        relativehumidity_2m: '%',
        precipitation_probability: '%',
        cloudcover: '%',
        windspeed_10m: 'km/h',
      },
      hourly: {
        time: ['2023-10-09T00:00', '2023-10-09T01:00', '2023-10-09T02:00'],
        temperature_2m: [19.5, 19.4, 18.9],
        relativehumidity_2m: [93, 94, 94],
        precipitation_probability: [0, 0, 0],
        weathercode: [2, 45, 45],
        cloudcover: [82, 62, 31],
        windspeed_10m: [2.1, 3.3, 4.5],
      },
    };

    const array = service.createForecastArray(testObj);

    expect(array.length).toEqual(3);
  });

  it('forecast array should contain forecast', () => {
    const testObj = {
      hourly_units: {
        temperature_2m: '°C',
        relativehumidity_2m: '%',
        precipitation_probability: '%',
        cloudcover: '%',
        windspeed_10m: 'km/h',
      },
      hourly: {
        time: ['2023-10-09T00:00', '2023-10-09T01:00', '2023-10-09T02:00'],
        temperature_2m: [19.5, 19.4, 18.9],
        relativehumidity_2m: [93, 94, 94],
        precipitation_probability: [0, 0, 0],
        weathercode: [2, 45, 45],
        cloudcover: [82, 62, 31],
        windspeed_10m: [2.1, 3.3, 4.5],
      },
    };

    const comparisonObj = {
      time: new Date('2023-10-09T00:00'),
      cloudCover: 82,
      windSpeed: 1,
      precipitation: 0,
      humidity: 93,
      temperature: 19.5,
      weatherCode: 2,
      cloudCoverUnit: '%',
      windSpeedUnit: 'Kn',
      precipitationUnit: '%',
      humidityUnit: '%',
      temperatureUnit: '°C',
    };

    const array = service.createForecastArray(testObj);

    expect(array[0]).toEqual(comparisonObj);
  });

  it('should convert Km/h to Knot', () => {

    const startingSpeedArray = [100, 50, 255, 0, 1];

    const speedKnArray = [54, 27, 138, 0, 1];

    const result = startingSpeedArray.map(speed => service.fromKmHToKnot(speed)) ;

    expect(result).toEqual(speedKnArray);

  })

>>>>>>> adcf55854059527e461402a4ea8ff564880a9a6b
});
